#:schema https://raw.githubusercontent.com/cloudflare/workers-sdk/main/packages/wrangler/config-schema.json
name = "mattico-website"
pages_build_output_dir = "./public"
compatibility_date = "2025-04-01"
