#:schema https://raw.githubusercontent.com/cloudflare/workers-sdk/main/packages/wrangler/config-schema.json
name = "mattico-website"
main = "src/worker.js"
compatibility_date = "2025-04-01"

[assets]
directory = "./public"
binding = "ASSETS"

routes = [
  { pattern = "mattico.net", custom_domain = true },
  { pattern = "www.mattico.net", custom_domain = true },
]
