#:schema https://raw.githubusercontent.com/cloudflare/workers-sdk/main/packages/wrangler/config-schema.json
name = "mattico-website"
compatibility_date = "2026-02-11"
main = "index.js"

[observability]
enabled = true

[assets]
directory = "./public"
binding = "ASSETS"

